Return dummy patchStyles function if document is not defined
This fixes an error when using elm-ui with rtfeldman/elm-css.
Running elm-css resulted in the following error without this fix:

	Error: ReferenceError: document is not defined

This happened because elm-css is run using node when generating the css
output and it doesn't have `document` defined.